### ISSUE TITLE
blosc issue w/ new branch? 

### ISSUE THREAD

**Issue by alexbaden** [openconnectome/open-connectome#147]
When running CAJAL unit tests, I get the following error when posting an HDF5 object to this URL:
```
/ocp/ocp/ca/apiUnitTests/apiUnitTestKasthuri/hdf5/1/2560,3760/1000,2200/128,144/overwrite/
```
Error:
```
[30/Sep/2015 13:48:04] ERROR [ocp:views:101]Unknown exception in getCutout.
Traceback (most recent call last):
  File "/usr/share/ocp/open-connectome/django/ocpca/views.py", line 86, in cutout
    django.http.HttpResponse(ocpcarest.putCutout(webargs, request.body))
  File "/usr/share/ocp/open-connectome/ocpca/ocpcarest.py", line 784, in putCutout
    return selectPost ( rangeargs, proj, db, postdata )
  File "/usr/share/ocp/open-connectome/ocpca/ocpcarest.py", line 730, in selectPost
    db.annotateDense ( ch, corner, resolution, voxarray, conflictopt )
  File "/usr/share/ocp/open-connectome/ocpca/ocpcadb.py", line 720, in annotateDense
    self.annoIdx.updateIndexDense(ch, index_dict, resolution)
  File "/usr/share/ocp/open-connectome/ocpca/annindex.py", line 71, in updateIndexDense
    curindex = self.getIndex(ch, key,resolution,True)
  File "/usr/share/ocp/open-connectome/ocpca/annindex.py", line 49, in getIndex
    return blosc.unpack_array(idxstr)
  File "/usr/share/ocp/virtualenvs/ocp/lib/python2.7/site-packages/blosc/toplevel.py", line 641, in unpack_array
    pickled_array = _ext.decompress(packed_array)
error: Error 904 : not a Blosc buffer or header info is corrupted
[30/Sep/2015 13:48:04] ERROR [django.request:base:256]Internal Server Error: /ocp/ocp/ca/apiUnitTests/apiUnitTestKasthuri/hdf5/1/2560,3760/1000,2200/128,144/overwrite/
Traceback (most recent call last):
  File "/usr/share/ocp/virtualenvs/ocp/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/share/ocp/open-connectome/django/ocpca/views.py", line 102, in cutout
    raise OCPCAError("Unknown exception in getCutout")
OCPCAError: 'Unknown exception in getCutout'
```
HDF5 file emailed separately, since github doesn't support attaching HDF5 files.

**Comment by willgray** [comment]
This is science critical.  We fail non-deterministically.

workCounter = 2
failCounter = 3


Here's a script:


workCounter = 0;
failCounter = 0;

for i = 1:5 %make this higher if you want
    
    token = <in your email>
    server = 'openconnecto.me';
    channel = 'annotation';
    oo = OCP();
    oo.setAnnoToken(token);
    
    labels = zeros(100,100,5);
    labels(50:70,50:70,2:4) = 1;
    
    RAMONVol = RAMONVolume();
    RAMONVol.setChannel('annotation');
    
    RAMONVol.setDataType(eRAMONChannelDataType.uint32)
    RAMONVol.setChannelType(eRAMONChannelType.annotation);
    RAMONVol.setResolution(5);
    
    RAMONVol.setXyzOffset([0,0,1]);
    RAMONVol.setCutout(labels);
    
    try
        cubeUploadDense(server, token, channel, RAMONVol, 'RAMONSegment', 0)
        workCounter = workCounter + 1;
    catch
        failCounter = failCounter + 1;
    end
end

**Comment by willgray** [comment]
cubeuploaddense is part of cajal

**Comment by kunallillaney** [comment]
This is now fixed on dsp29. Propagating changes on other servers.

**Comment by willgray** [comment]
Thanks!!!!
