### ISSUE TITLE
When creating a float32 probabilitymap and posting an hdf5 file, error occurs

### ISSUE THREAD

**Issue by alexbaden** [openconnectome/open-connectome#36]
I don't know enough about how the probabilitymap stuff was written to make any headway on this...

```
[16/May/2015 19:23:41] ERROR [ocp:views:86] Unknown exception in getCutout.
Traceback (most recent call last):
  File "./ocpca/views.py", line 71, in cutout
    django.http.HttpResponse(ocpcarest.putCutout(webargs,request.body))
  File "/var/www/ocp/open-connectome/ocpca/ocpcarest.py", line 569, in putCutout
    return selectPost ( rangeargs, proj, db, postdata )
  File "/var/www/ocp/open-connectome/ocpca/ocpcarest.py", line 488, in selectPost
    if voxarray.dtype == ocpcaproj.OCP_dtypetonp[ch.getDataType()]:
KeyError: u'float32'
```

Looks like OCP_dtypetonp wasn't updated for the new schema? 

```
OCP_dtypetonp = {'uint8':np.uint8,'uint16':np.uint16,'uint32':np.uint32,'rgb32':np.uint32,'rgb64':np.uint64,'probability':np.float32
```

Or I'm just confused...

**Comment by kunallillaney** [comment]
@alexbaden Will look into this.

**Comment by kunallillaney** [comment]
Writing a test for this. Cutouts, Posts and propagate will be fixed.

**Comment by kunallillaney** [comment]
Done.
