### ISSUE TITLE
When posting a probability map, entityid is referenced before assignment

### ISSUE THREAD

**Issue by alexbaden** [openconnectome/open-connectome#47]
```
[04/Jun/2015 16:23:25] ERROR [ocp:views:84] Unknown exception in getCutout.
Traceback (most recent call last):
  File "/Users/abaden/Projects/open-connectome/django/ocpca/views.py", line 69, in cutout
    django.http.HttpResponse(ocpcarest.putCutout(webargs,request.body))
  File "/Users/abaden/Projects/open-connectome/ocpca/ocpcarest.py", line 559, in putCutout
    return selectPost ( rangeargs, proj, db, postdata )
  File "/Users/abaden/Projects/open-connectome/ocpca/ocpcarest.py", line 530, in selectPost
    return str(entityid)
UnboundLocalError: local variable 'entityid' referenced before assignment
[04/Jun/2015 16:23:25] ERROR [django.request:base:231] Internal Server Error: /ocp/ca/apiUnitTests/apiUnitTestKasthuriProb/hdf5/1/2560,3584/1000,2024/64,112/overwrite/
Traceback (most recent call last):
  File "/Users/abaden/.virtualenvs/ocp/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/abaden/Projects/open-connectome/django/ocpca/views.py", line 85, in cutout
    raise OCPCAError("Unknow exception in getCutout")
OCPCAError: 'Unknow exception in getCutout'
```

**Comment by kunallillaney** [comment]
Did you do a pull on kl-d7?

**Comment by alexbaden** [comment]
Yes

**Comment by kunallillaney** [comment]
I need an hdf5 file for  this because it passes all my probability map tests so am not sure if the problem is there.

**Comment by alexbaden** [comment]
This looks like the problem:

(Pdb) p ocpcaproj.IMAGE_CHANNELS

['image', 'probmap']

(Pdb) p ch.getChannelType

<bound method OCPCAChannel.getChannelType of <ocpcaproj.OCPCAChannel
instance at 0x10724ecf8>>

(Pdb) p ch.getChannelType()

u'PROBABILITY_MAP'


We need to standardize on a way of describing these things -- either
PROBABILITY_MAP or probmap is fine, but I need to know ASAP.

**Comment by alexbaden** [comment]
Sorry, that's line 494

if ch.getChannelType() in ocpcaproj.IMAGE_CHANNELS:

**Comment by kunallillaney** [comment]
We are going with probmap. I will update this in GUI as well.

**Comment by alexbaden** [comment]
ch.getChannelType returns the other form... I can't do any work on CAJAL
until this is standardized across everything.

**Comment by kunallillaney** [comment]
Because Randal has PROBABILITY_MAP in the GUI and probmap in the code. I will standardize it across all channel types and make a push soon.

**Comment by kunallillaney** [comment]
Pushed.
