### ISSUE TITLE
bug in id service

### ISSUE THREAD

**Issue by alexbaden** [openconnectome/open-connectome#50]
When calling /ocp/ca/kharris15apical/annos/id/3/582/530/88/ I get the following:
```
[09/Jun/2015 18:46:24] "GET //ocp/ca/kharris15apical/annos/id/3/582/530/88/ HTTP/1.1" 404 3431
[09/Jun/2015 18:46:28] ERROR [ocp:views:86] Unknown exception in getCutout.
Traceback (most recent call last):
  File "/Users/abaden/Projects/open-connectome/django/ocpca/views.py", line 62, in cutout
    return django.http.HttpResponse(ocpcarest.getCutout(webargs))
  File "/Users/abaden/Projects/open-connectome/ocpca/ocpcarest.py", line 547, in getCutout
    return selectService ( service, webargs, proj, db )
  File "/Users/abaden/Projects/open-connectome/ocpca/ocpcarest.py", line 388, in selectService
    return annId ( webargs, proj, db )
  File "/Users/abaden/Projects/open-connectome/ocpca/ocpcarest.py", line 346, in annId
    (resolution, voxel) = restargs.voxel ( imageargs, proj.datasetcfg )
  File "/Users/abaden/Projects/open-connectome/util/restargs.py", line 147, in voxel
    if not ( datasetcfg.checkCube ( resolution, [x,y,z], [x+1,y+1,z+1] )):
TypeError: checkCube() takes exactly 5 arguments (4 given)
[09/Jun/2015 18:46:28] ERROR [django.request:base:231] Internal Server Error: /ocp/ca/kharris15apical/annos/id/3/582/530/88/
Traceback (most recent call last):
  File "/Users/abaden/.virtualenvs/ocp/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/abaden/Projects/open-connectome/django/ocpca/views.py", line 87, in cutout
    raise OCPCAError("Unknow exception in getCutout")
OCPCAError: 'Unknow exception in getCutout'
[09/Jun/2015 18:46:28] "GET /ocp/ca/kharris15apical/annos/id/3/582/530/88/ HTTP/1.1" 500 62955
```

Not sure what exactly is going on. Feel free to test on bv1.

**Comment by alexbaden** [comment]
It would be nice to have this fixed for demoing purposes tomorrow, but no big deal if it's not.

**Comment by kunallillaney** [comment]
Done. Pull from kl-d7.

**Comment by alexbaden** [comment]
Working -- awesome!!
