### ISSUE TITLE
queryAnnoObjects failing (ocpcarest)

### ISSUE THREAD

**Issue by alexbaden** [openconnectome/open-connectome#52]
Two errors:

1) Looks like resolution isn't set in the right place:
```
1192           offset = proj.datasetcfg.offset[resolution]
1193           corner = (h5f['XYZOFFSET'][0]-offset[0],h5f['XYZOFFSET'][1]-offset[1],h5f['     XYZOFFSET'][2]-offset[2])
1194           dim = h5f['CUTOUTSIZE'][:]
1195           resolution = h5f['RESOLUTION'][0]
```
Moving the resolution (line 1195) up to line 1191 seemed to fix that problem (did not commit). But then I got this error:
```
Traceback (most recent call last):
  File "/Users/abaden/Projects/open-connectome/django/ocpca/views.py", line 139, in queryObjects
    return django.http.HttpResponse(ocpcarest.queryAnnoObjects(webargs,request.body), content_type="product/hdf5")
  File "/Users/abaden/Projects/open-connectome/ocpca/ocpcarest.py", line 1197, in queryAnnoObjects
    if not proj.datasetcfg.checkCube( resolution, corner[0], corner[0]+dim[0], corner[1], corner[1]+dim[1], corner[2], corner[2]+dim[2] ):
TypeError: checkCube() takes at most 5 arguments (8 given)
```
I think Kunal already fixed this in a previous query?

**Comment by alexbaden** [comment]
Here's a sample URL:
http://localhost:8000/ocp/ca/apiUnitTests/apiUnitTestKasthuri/query/status/0/type/2/

apiUnitTests is a project built off the Kasthuri dataset (is empty)
apiUnitTestKasthuri is just an annotation channel.

**Comment by kunallillaney** [comment]
Done and pushed. Some other bugs resolved as well.
