### ISSUE TITLE
symbol not found on local server after pulling new master

### ISSUE THREAD

**Issue by alexbaden** [openconnectome/open-connectome#98]
```
[19/Aug/2015 12:30:26] ERROR [django.request:base:231]Internal Server Error: /ca/unittest/IMAGE1,IMAGE2/npz/0/3072,3584/4096,4608/200,201/
Traceback (most recent call last):
  File "/Users/abaden/.virtualenvs/ocp/lib/python2.7/site-packages/django/core/handlers/base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/abaden/.virtualenvs/ocp/lib/python2.7/site-packages/django/core/urlresolvers.py", line 343, in resolve
    for pattern in self.url_patterns:
  File "/Users/abaden/.virtualenvs/ocp/lib/python2.7/site-packages/django/core/urlresolvers.py", line 372, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/abaden/.virtualenvs/ocp/lib/python2.7/site-packages/django/core/urlresolvers.py", line 366, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/abaden/Projects/open-connectome/django/OCP/urls.py", line 29, in <module>
    url(r'^ocpuser/', include('ocpuser.urls')),
  File "/Users/abaden/.virtualenvs/ocp/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 28, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/abaden/Projects/open-connectome/django/ocpuser/urls.py", line 16, in <module>
    from ocpuser.views import *
  File "/Users/abaden/Projects/open-connectome/django/ocpuser/views.py", line 41, in <module>
    import ocpcarest
  File "/Users/abaden/Projects/open-connectome/ocpca/ocpcarest.py", line 33, in <module>
    import anncube
  File "/Users/abaden/Projects/open-connectome/ocpca/anncube.py", line 21, in <module>
    import ocplib
  File "/Users/abaden/Projects/open-connectome/ocpca/ocplib.py", line 72, in <module>
    ocplib.unique.argtypes = [ array_1d_uint32, array_1d_uint32, cp.c_int ]
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(0x7fea5beb58f0, unique): symbol not found
^C[19/Aug/2015 12:30:26] "GET /ca/unittest/IMAGE1,IMAGE2/npz/0/3072,3584/4096,4608/200,201/ HTTP/1.1" 500 164757
```

what is going wrong? I need to try and fix this ASAP so I can work on ocpviz at Allen today.

**Comment by kunallillaney** [comment]
this is no bug. Just copy the new makefile which was pushed. that will resolve this.

**Comment by alexbaden** [comment]
I used both new makefiles and ran make clean then make.

**Comment by kunallillaney** [comment]
Yes. You need to copy makefile_LINUX to makefile. Did you do that?
